# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 06:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bargainflow', '0004_auto_20170402_0626'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=datetime.datetime(2017, 4, 2, 6, 26, 40, 344814))),
                ('description', models.TextField()),
                ('rating', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative'), ('U', 'Undeclared')], default='U', max_length=1)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bargainflow.Commission')),
                ('opinion_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
