# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 13:01
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('moneyflow', '0005_auto_20170409_1406'),
        ('bargainflow', '0006_merge_20170410_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='money',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='money',
                                    to='moneyflow.CurrencyAccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commission',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 4, 10, 14, 59, 39, 84416)),
        ),
    ]
